//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeneyim
    {
        public int DeneyimID { get; set; }
        public string DeneyimUnvan { get; set; }
        public string DeneyimKurulus { get; set; }
        public string DeneyimAciklama { get; set; }
        public string DeneyimBaslangicTarih { get; set; }
        public string DeneyimBitisTarih { get; set; }
    }
}
