//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEgitim
    {
        public int EgitimID { get; set; }
        public string EgitimOkulAd { get; set; }
        public string EgitimBolumAd { get; set; }
        public string EgitimAciklama { get; set; }
        public string EgitimGNO { get; set; }
        public string EgitimBaslangicTarih { get; set; }
        public string EgitimBitisTarih { get; set; }
    }
}
