//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkimda
    {
        public int HakkimdaID { get; set; }
        public string HakkimdaAd { get; set; }
        public string HakkimdaSoyad { get; set; }
        public string HakkimdaAdres { get; set; }
        public string HakkimdaTelefon { get; set; }
        public string HakkimdaMail { get; set; }
        public string HakkimdaAciklama { get; set; }
        public string HakkimdaGorsel { get; set; }
    }
}
