//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSosyalMedya
    {
        public int SosyalID { get; set; }
        public string SosyalAd { get; set; }
        public string SosyalLink { get; set; }
        public Nullable<bool> SosyalDurum { get; set; }
        public string Sosyalicon { get; set; }
    }
}
