//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSertifika
    {
        public int SertifikaID { get; set; }
        public string SertifikaAd { get; set; }
        public string SertifikaKurulus { get; set; }
        public string SertifikaTarih { get; set; }
    }
}
